#ifndef __DIAGINFO_MAP
#define __DIAGINFO_MAP(x,y,z,k) 
#endif
#ifndef __DIAGINFO_MODULE_MAP
#define __DIAGINFO_MODULE_MAP(x) 
#endif
__DIAGINFO_MAP(L3_ECC_1BIT_ERROR, SoC_AP, Warning, HW)
__DIAGINFO_MAP(CPU_UP_FAIL, SoC_AP, Critical, HW)
__DIAGINFO_MAP(LPM3_DDR_FAIl, DDR, Critical, HW)
__DIAGINFO_MODULE_MAP(SoC_AP)
__DIAGINFO_MODULE_MAP(DDR)
