# MD5: 5f27aa2a05d0032b3cf51156d03504c0
CFG_FEATURE_MEMCPY_REBOOT_CFG                   := FEATURE_ON
CFG_FEATURE_AT_NV_WRITE_SUPPORT                 := YES
CFG_FEATURE_READ_LOG_FILTER_CFG                 := YES
CFG_FEATURE_DEBUG_APP_PORT                      := FEATURE_ON
CFG_FEATURE_PHONE_ENG_AT_CMD                    := FEATURE_ON
CFG_FEATURE_DEBUG_PRINT_ADDRESS                 := FEATURE_ON
