/* MD5: be57c00c152d4700cf2aa71f4fa4edba*/
#if !defined(__PRODUCT_CONFIG_PAM_H__)
#define __PRODUCT_CONFIG_PAM_H__

#ifndef BBP_MASTER_NONE
#define BBP_MASTER_NONE 0 
#endif 

#ifndef BBP_MASTER_VER1
#define BBP_MASTER_VER1 1 
#endif 

#ifndef BBP_MASTER_VER2
#define BBP_MASTER_VER2 2 
#endif 

#ifndef BBP_MASTER_VER3
#define BBP_MASTER_VER3 3 
#endif 

#ifndef BBP_MASTER_VER4
#define BBP_MASTER_VER4 4 
#endif 

#ifndef BBP_MASTER_VER5
#define BBP_MASTER_VER5 5 
#endif 

#ifndef BBP_MASTER_VER6
#define BBP_MASTER_VER6 6 
#endif 

#ifndef FEATURE_BBP_MASTER_VER
#define FEATURE_BBP_MASTER_VER (BBP_MASTER_VER5) 
#endif 

#ifndef FEATURE_POWER_TIMER
#define FEATURE_POWER_TIMER FEATURE_ON 
#endif 

#ifndef FEATURE_UE_UICC_MULTI_APP_SUPPORT
#define FEATURE_UE_UICC_MULTI_APP_SUPPORT FEATURE_ON 
#endif 

#ifndef FEATURE_VSIM
#define FEATURE_VSIM FEATURE_ON 
#endif 

#ifndef FEATURE_GUC_BBP_TRIG
#define FEATURE_GUC_BBP_TRIG FEATURE_ON 
#endif 

#ifndef FEATURE_CSIM_NONCHECK
#define FEATURE_CSIM_NONCHECK FEATURE_OFF 
#endif 

#ifndef FEATURE_GUC_BBP_TRIG_NEWVERSION
#define FEATURE_GUC_BBP_TRIG_NEWVERSION FEATURE_ON 
#endif 

#ifndef FEATURE_VOS_REDUCE_MEM_CFG
#define FEATURE_VOS_REDUCE_MEM_CFG FEATURE_OFF 
#endif 

#ifndef FEATURE_RTC_TIMER_DBG
#define FEATURE_RTC_TIMER_DBG FEATURE_ON 
#endif 

#ifndef FEATURE_PHONE_SC
#define FEATURE_PHONE_SC FEATURE_ON 
#endif 

#ifndef FEATURE_SC_NETWORK_UPDATE
#define FEATURE_SC_NETWORK_UPDATE FEATURE_OFF 
#endif 

#ifndef FEATURE_SC_SIGNATURE_UPDATE
#define FEATURE_SC_SIGNATURE_UPDATE FEATURE_ON 
#endif 

#ifndef FEATURE_VSIM_ICC_SEC_CHANNEL
#define FEATURE_VSIM_ICC_SEC_CHANNEL FEATURE_ON 
#endif 

#ifndef FEATURE_BOSTON_AFTER_FEATURE
#define FEATURE_BOSTON_AFTER_FEATURE FEATURE_ON 
#endif 

#ifndef FEATURE_XSIM
#define FEATURE_XSIM FEATURE_OFF 
#endif 

#ifndef FEATURE_SCI_SWITCH_OPTIMIZE
#define FEATURE_SCI_SWITCH_OPTIMIZE FEATURE_ON 
#endif 

#ifndef FEATURE_VOS_18H_TIMER
#define FEATURE_VOS_18H_TIMER FEATURE_OFF 
#endif 

#ifndef FEATURE_SET_C1C2_VALUE
#define FEATURE_SET_C1C2_VALUE FEATURE_ON 
#endif 

#endif /*__PRODUCT_CONFIG_H__*/ 
