ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/csi
ccflags-y += -Idrivers/media/huawei/camera/platform
ccflags-y += -Idrivers/media/huawei/camera/fpga

obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX600HYBRID) += imx600hybrid.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_OV9282) += ov9282.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_OV9282) += ov9286.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX576) += imx576.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_OV8856) += ov8856.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_OV08A10) += ov08a10.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_CAMKIT) += hisensor.o
obj-y += m25p80_norflash.o

