//****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co., Ltd.
// File name     :  mfnr_reg_offset_field.h
// Author        :  HerveDANIEL
// Version       :  1.0 
// Date          :  2018-01-03
// Description   :  Define all registers/tables for HiStarISP
// Others        :  Generated automatically by nManager V4.0 
// History       :  HerveDANIEL 2018-01-03 Create file
//******************************************************************************

#ifndef __MFNR_REG_OFFSET_FIELD_H__
#define __MFNR_REG_OFFSET_FIELD_H__

#define MFNR_GHOST_STATS_CROP_H_EN_LEN    1  
#define MFNR_GHOST_STATS_CROP_H_EN_OFFSET 5  
#define MFNR_GHOST_MASK_WR_EN_LEN         1  
#define MFNR_GHOST_MASK_WR_EN_OFFSET      4  
#define MFNR_UV_PACK_LEN                  1  
#define MFNR_UV_PACK_OFFSET               3  
#define MFNR_UV_UNPACK_LEN                1  
#define MFNR_UV_UNPACK_OFFSET             2  
#define MFNR_OP_MODE_LEN                  2  
#define MFNR_OP_MODE_OFFSET               0  

#define MFNR_HEIGHT_LEN        13 
#define MFNR_HEIGHT_OFFSET     16 
#define MFNR_WIDTH_LEN         10 
#define MFNR_WIDTH_OFFSET      0  

#define MFNR_GHOST_MASK_TH_LEN    8  
#define MFNR_GHOST_MASK_TH_OFFSET 0  

#define MFNR_US16_CROP_H_END_LEN      11 
#define MFNR_US16_CROP_H_END_OFFSET   16 
#define MFNR_US16_CROP_H_START_LEN    11 
#define MFNR_US16_CROP_H_START_OFFSET 0  

#define MFNR_STATS_CROP_H_END_LEN      9  
#define MFNR_STATS_CROP_H_END_OFFSET   16 
#define MFNR_STATS_CROP_H_START_LEN    9  
#define MFNR_STATS_CROP_H_START_OFFSET 0  

#define MFNR_SUBSCALE_LEN           8  
#define MFNR_SUBSCALE_OFFSET        20 
#define MFNR_GHOST_REGION_TH_LEN    8  
#define MFNR_GHOST_REGION_TH_OFFSET 12 
#define MFNR_WEIGHT_LEN             9  
#define MFNR_WEIGHT_OFFSET          0  

#define MFNR_SIGMA_LEN                        8  
#define MFNR_SIGMA_OFFSET                     24 
#define MFNR_JUDGE_GRAD_REGION_TH_LEN         8  
#define MFNR_JUDGE_GRAD_REGION_TH_OFFSET      16 
#define MFNR_MIN_GRAD2SIGMA_SCALE_BKPT_LEN    8  
#define MFNR_MIN_GRAD2SIGMA_SCALE_BKPT_OFFSET 8  
#define MFNR_MAX_GRAD2SIGMA_SCALE_BKPT_LEN    8  
#define MFNR_MAX_GRAD2SIGMA_SCALE_BKPT_OFFSET 0  

#define MFNR_SUP_BLEND_SCALE_LEN              5  
#define MFNR_SUP_BLEND_SCALE_OFFSET           24 
#define MFNR_SUP_MEAN2BLEND_TH_LEN            5  
#define MFNR_SUP_MEAN2BLEND_TH_OFFSET         16 
#define MFNR_MIN_GRAD2BLEND_SCALE_BKPT_LEN    8  
#define MFNR_MIN_GRAD2BLEND_SCALE_BKPT_OFFSET 8  
#define MFNR_MAX_GRAD2BLEND_SCALE_BKPT_LEN    8  
#define MFNR_MAX_GRAD2BLEND_SCALE_BKPT_OFFSET 0  

#define MFNR_MEAN2SIGMA_0_LEN    8  
#define MFNR_MEAN2SIGMA_0_OFFSET 0  

#define MFNR_MEAN2SIGMA_1_LEN    8  
#define MFNR_MEAN2SIGMA_1_OFFSET 0  

#define MFNR_MEAN2SIGMA_2_LEN    8  
#define MFNR_MEAN2SIGMA_2_OFFSET 0  

#define MFNR_MEAN2SIGMA_3_LEN    8  
#define MFNR_MEAN2SIGMA_3_OFFSET 0  

#define MFNR_MEAN2SIGMA_4_LEN    8  
#define MFNR_MEAN2SIGMA_4_OFFSET 0  

#define MFNR_MEAN2SIGMA_5_LEN    8  
#define MFNR_MEAN2SIGMA_5_OFFSET 0  

#define MFNR_MEAN2SIGMA_6_LEN    8  
#define MFNR_MEAN2SIGMA_6_OFFSET 0  

#define MFNR_MEAN2SIGMA_7_LEN    8  
#define MFNR_MEAN2SIGMA_7_OFFSET 0  

#define MFNR_MEAN2SIGMA_8_LEN    8  
#define MFNR_MEAN2SIGMA_8_OFFSET 0  

#define MFNR_MEAN2SIGMA_9_LEN    8  
#define MFNR_MEAN2SIGMA_9_OFFSET 0  

#define MFNR_MEAN2SIGMA_10_LEN    8  
#define MFNR_MEAN2SIGMA_10_OFFSET 0  

#define MFNR_MEAN2SIGMA_11_LEN    8  
#define MFNR_MEAN2SIGMA_11_OFFSET 0  

#define MFNR_MEAN2SIGMA_12_LEN    8  
#define MFNR_MEAN2SIGMA_12_OFFSET 0  

#define MFNR_MEAN2SIGMA_13_LEN    8  
#define MFNR_MEAN2SIGMA_13_OFFSET 0  

#define MFNR_MEAN2SIGMA_14_LEN    8  
#define MFNR_MEAN2SIGMA_14_OFFSET 0  

#define MFNR_MEAN2SIGMA_15_LEN    8  
#define MFNR_MEAN2SIGMA_15_OFFSET 0  

#define MFNR_MEAN2SIGMA_16_LEN    8  
#define MFNR_MEAN2SIGMA_16_OFFSET 0  

#define MFNR_MEAN2SIGMA_17_LEN    8  
#define MFNR_MEAN2SIGMA_17_OFFSET 0  

#define MFNR_MEAN2SIGMA_18_LEN    8  
#define MFNR_MEAN2SIGMA_18_OFFSET 0  

#define MFNR_MEAN2SIGMA_19_LEN    8  
#define MFNR_MEAN2SIGMA_19_OFFSET 0  

#define MFNR_MEAN2SIGMA_20_LEN    8  
#define MFNR_MEAN2SIGMA_20_OFFSET 0  

#define MFNR_MEAN2SIGMA_21_LEN    8  
#define MFNR_MEAN2SIGMA_21_OFFSET 0  

#define MFNR_MEAN2SIGMA_22_LEN    8  
#define MFNR_MEAN2SIGMA_22_OFFSET 0  

#define MFNR_MEAN2SIGMA_23_LEN    8  
#define MFNR_MEAN2SIGMA_23_OFFSET 0  

#define MFNR_MEAN2SIGMA_24_LEN    8  
#define MFNR_MEAN2SIGMA_24_OFFSET 0  

#define MFNR_MEAN2SIGMA_25_LEN    8  
#define MFNR_MEAN2SIGMA_25_OFFSET 0  

#define MFNR_GRAD2SIGMA_0_LEN    8  
#define MFNR_GRAD2SIGMA_0_OFFSET 0  

#define MFNR_GRAD2SIGMA_1_LEN    8  
#define MFNR_GRAD2SIGMA_1_OFFSET 0  

#define MFNR_GRAD2SIGMA_2_LEN    8  
#define MFNR_GRAD2SIGMA_2_OFFSET 0  

#define MFNR_GRAD2SIGMA_3_LEN    8  
#define MFNR_GRAD2SIGMA_3_OFFSET 0  

#define MFNR_GRAD2SIGMA_4_LEN    8  
#define MFNR_GRAD2SIGMA_4_OFFSET 0  

#define MFNR_GRAD2SIGMA_5_LEN    8  
#define MFNR_GRAD2SIGMA_5_OFFSET 0  

#define MFNR_GRAD2SIGMA_6_LEN    8  
#define MFNR_GRAD2SIGMA_6_OFFSET 0  

#define MFNR_GRAD2SIGMA_7_LEN    8  
#define MFNR_GRAD2SIGMA_7_OFFSET 0  

#define MFNR_GRAD2SIGMA_8_LEN    8  
#define MFNR_GRAD2SIGMA_8_OFFSET 0  

#define MFNR_GRAD2SIGMA_9_LEN    8  
#define MFNR_GRAD2SIGMA_9_OFFSET 0  

#define MFNR_GRAD2SIGMA_10_LEN    8  
#define MFNR_GRAD2SIGMA_10_OFFSET 0  

#define MFNR_GRAD2SIGMA_11_LEN    8  
#define MFNR_GRAD2SIGMA_11_OFFSET 0  

#define MFNR_GRAD2SIGMA_12_LEN    8  
#define MFNR_GRAD2SIGMA_12_OFFSET 0  

#define MFNR_GRAD2SIGMA_13_LEN    8  
#define MFNR_GRAD2SIGMA_13_OFFSET 0  

#define MFNR_GRAD2SIGMA_14_LEN    8  
#define MFNR_GRAD2SIGMA_14_OFFSET 0  

#define MFNR_GRAD2SIGMA_15_LEN    8  
#define MFNR_GRAD2SIGMA_15_OFFSET 0  

#define MFNR_GRAD2SIGMA_16_LEN    8  
#define MFNR_GRAD2SIGMA_16_OFFSET 0  

#define MFNR_GRAD2SIGMA_17_LEN    8  
#define MFNR_GRAD2SIGMA_17_OFFSET 0  

#define MFNR_GRAD2SIGMA_18_LEN    8  
#define MFNR_GRAD2SIGMA_18_OFFSET 0  

#define MFNR_GRAD2SIGMA_19_LEN    8  
#define MFNR_GRAD2SIGMA_19_OFFSET 0  

#define MFNR_GRAD2SIGMA_20_LEN    8  
#define MFNR_GRAD2SIGMA_20_OFFSET 0  

#define MFNR_GRAD2SIGMA_21_LEN    8  
#define MFNR_GRAD2SIGMA_21_OFFSET 0  

#define MFNR_GRAD2SIGMA_22_LEN    8  
#define MFNR_GRAD2SIGMA_22_OFFSET 0  

#define MFNR_GRAD2SIGMA_23_LEN    8  
#define MFNR_GRAD2SIGMA_23_OFFSET 0  

#define MFNR_GRAD2SIGMA_24_LEN    8  
#define MFNR_GRAD2SIGMA_24_OFFSET 0  

#define MFNR_GRAD2SIGMA_25_LEN    8  
#define MFNR_GRAD2SIGMA_25_OFFSET 0  

#define MFNR_GRAD2SIGMA_26_LEN    8  
#define MFNR_GRAD2SIGMA_26_OFFSET 0  

#define MFNR_GRAD2SIGMA_27_LEN    8  
#define MFNR_GRAD2SIGMA_27_OFFSET 0  

#define MFNR_GRAD2SIGMA_28_LEN    8  
#define MFNR_GRAD2SIGMA_28_OFFSET 0  

#define MFNR_GRAD2SIGMA_29_LEN    8  
#define MFNR_GRAD2SIGMA_29_OFFSET 0  

#define MFNR_GRAD2SIGMA_30_LEN    8  
#define MFNR_GRAD2SIGMA_30_OFFSET 0  

#define MFNR_GRAD2SIGMA_31_LEN    8  
#define MFNR_GRAD2SIGMA_31_OFFSET 0  

#define MFNR_GRAD2SIGMA_32_LEN    8  
#define MFNR_GRAD2SIGMA_32_OFFSET 0  

#define MFNR_GRAD2SIGMA_33_LEN    8  
#define MFNR_GRAD2SIGMA_33_OFFSET 0  

#define MFNR_GRAD2SIGMA_34_LEN    8  
#define MFNR_GRAD2SIGMA_34_OFFSET 0  

#define MFNR_GRAD2SIGMA_35_LEN    8  
#define MFNR_GRAD2SIGMA_35_OFFSET 0  

#define MFNR_GRAD2SIGMA_36_LEN    8  
#define MFNR_GRAD2SIGMA_36_OFFSET 0  

#define MFNR_GRAD2SIGMA_37_LEN    8  
#define MFNR_GRAD2SIGMA_37_OFFSET 0  

#define MFNR_GRAD2SIGMA_38_LEN    8  
#define MFNR_GRAD2SIGMA_38_OFFSET 0  

#define MFNR_GRAD2SIGMA_39_LEN    8  
#define MFNR_GRAD2SIGMA_39_OFFSET 0  

#define MFNR_GRAD2SIGMA_40_LEN    8  
#define MFNR_GRAD2SIGMA_40_OFFSET 0  

#define MFNR_GRAD2SIGMA_41_LEN    8  
#define MFNR_GRAD2SIGMA_41_OFFSET 0  

#define MFNR_GRAD2SIGMA_42_LEN    8  
#define MFNR_GRAD2SIGMA_42_OFFSET 0  

#define MFNR_GRAD2SIGMA_43_LEN    8  
#define MFNR_GRAD2SIGMA_43_OFFSET 0  

#define MFNR_GRAD2SIGMA_44_LEN    8  
#define MFNR_GRAD2SIGMA_44_OFFSET 0  

#define MFNR_GRAD2SIGMA_45_LEN    8  
#define MFNR_GRAD2SIGMA_45_OFFSET 0  

#define MFNR_GRAD2SIGMA_46_LEN    8  
#define MFNR_GRAD2SIGMA_46_OFFSET 0  

#define MFNR_GRAD2SIGMA_47_LEN    8  
#define MFNR_GRAD2SIGMA_47_OFFSET 0  

#define MFNR_GRAD2SIGMA_48_LEN    8  
#define MFNR_GRAD2SIGMA_48_OFFSET 0  

#define MFNR_GRAD2SIGMA_49_LEN    8  
#define MFNR_GRAD2SIGMA_49_OFFSET 0  

#define MFNR_GRAD2SIGMA_50_LEN    8  
#define MFNR_GRAD2SIGMA_50_OFFSET 0  

#define MFNR_GRAD2SIGMA_51_LEN    8  
#define MFNR_GRAD2SIGMA_51_OFFSET 0  

#define MFNR_GRAD2SIGMA_52_LEN    8  
#define MFNR_GRAD2SIGMA_52_OFFSET 0  

#define MFNR_GRAD2SIGMA_53_LEN    8  
#define MFNR_GRAD2SIGMA_53_OFFSET 0  

#define MFNR_GRAD2SIGMA_54_LEN    8  
#define MFNR_GRAD2SIGMA_54_OFFSET 0  

#define MFNR_GRAD2SIGMA_55_LEN    8  
#define MFNR_GRAD2SIGMA_55_OFFSET 0  

#define MFNR_GRAD2SIGMA_56_LEN    8  
#define MFNR_GRAD2SIGMA_56_OFFSET 0  

#define MFNR_GRAD2SIGMA_57_LEN    8  
#define MFNR_GRAD2SIGMA_57_OFFSET 0  

#define MFNR_GRAD2SIGMA_58_LEN    8  
#define MFNR_GRAD2SIGMA_58_OFFSET 0  

#define MFNR_GRAD2SIGMA_59_LEN    8  
#define MFNR_GRAD2SIGMA_59_OFFSET 0  

#define MFNR_GRAD2SIGMA_60_LEN    8  
#define MFNR_GRAD2SIGMA_60_OFFSET 0  

#define MFNR_GRAD2SIGMA_61_LEN    8  
#define MFNR_GRAD2SIGMA_61_OFFSET 0  

#define MFNR_GRAD2SIGMA_62_LEN    8  
#define MFNR_GRAD2SIGMA_62_OFFSET 0  

#define MFNR_GRAD2SIGMA_63_LEN    8  
#define MFNR_GRAD2SIGMA_63_OFFSET 0  

#define MFNR_GRAD2SIGMA_64_LEN    8  
#define MFNR_GRAD2SIGMA_64_OFFSET 0  

#define MFNR_MEAN2BLEND_0_LEN    8  
#define MFNR_MEAN2BLEND_0_OFFSET 0  

#define MFNR_MEAN2BLEND_1_LEN    8  
#define MFNR_MEAN2BLEND_1_OFFSET 0  

#define MFNR_MEAN2BLEND_2_LEN    8  
#define MFNR_MEAN2BLEND_2_OFFSET 0  

#define MFNR_MEAN2BLEND_3_LEN    8  
#define MFNR_MEAN2BLEND_3_OFFSET 0  

#define MFNR_MEAN2BLEND_4_LEN    8  
#define MFNR_MEAN2BLEND_4_OFFSET 0  

#define MFNR_MEAN2BLEND_5_LEN    8  
#define MFNR_MEAN2BLEND_5_OFFSET 0  

#define MFNR_MEAN2BLEND_6_LEN    8  
#define MFNR_MEAN2BLEND_6_OFFSET 0  

#define MFNR_MEAN2BLEND_7_LEN    8  
#define MFNR_MEAN2BLEND_7_OFFSET 0  

#define MFNR_MEAN2BLEND_8_LEN    8  
#define MFNR_MEAN2BLEND_8_OFFSET 0  

#define MFNR_MEAN2BLEND_9_LEN    8  
#define MFNR_MEAN2BLEND_9_OFFSET 0  

#define MFNR_MEAN2BLEND_10_LEN    8  
#define MFNR_MEAN2BLEND_10_OFFSET 0  

#define MFNR_MEAN2BLEND_11_LEN    8  
#define MFNR_MEAN2BLEND_11_OFFSET 0  

#define MFNR_MEAN2BLEND_12_LEN    8  
#define MFNR_MEAN2BLEND_12_OFFSET 0  

#define MFNR_MEAN2BLEND_13_LEN    8  
#define MFNR_MEAN2BLEND_13_OFFSET 0  

#define MFNR_MEAN2BLEND_14_LEN    8  
#define MFNR_MEAN2BLEND_14_OFFSET 0  

#define MFNR_MEAN2BLEND_15_LEN    8  
#define MFNR_MEAN2BLEND_15_OFFSET 0  

#define MFNR_MEAN2BLEND_16_LEN    8  
#define MFNR_MEAN2BLEND_16_OFFSET 0  

#define MFNR_MEAN2BLEND_17_LEN    8  
#define MFNR_MEAN2BLEND_17_OFFSET 0  

#define MFNR_MEAN2BLEND_18_LEN    8  
#define MFNR_MEAN2BLEND_18_OFFSET 0  

#define MFNR_MEAN2BLEND_19_LEN    8  
#define MFNR_MEAN2BLEND_19_OFFSET 0  

#define MFNR_MEAN2BLEND_20_LEN    8  
#define MFNR_MEAN2BLEND_20_OFFSET 0  

#define MFNR_MEAN2BLEND_21_LEN    8  
#define MFNR_MEAN2BLEND_21_OFFSET 0  

#define MFNR_MEAN2BLEND_22_LEN    8  
#define MFNR_MEAN2BLEND_22_OFFSET 0  

#define MFNR_MEAN2BLEND_23_LEN    8  
#define MFNR_MEAN2BLEND_23_OFFSET 0  

#define MFNR_MEAN2BLEND_24_LEN    8  
#define MFNR_MEAN2BLEND_24_OFFSET 0  

#define MFNR_MEAN2BLEND_25_LEN    8  
#define MFNR_MEAN2BLEND_25_OFFSET 0  

#define MFNR_GRAD2BLEND_0_LEN    5  
#define MFNR_GRAD2BLEND_0_OFFSET 0  

#define MFNR_GRAD2BLEND_1_LEN    5  
#define MFNR_GRAD2BLEND_1_OFFSET 0  

#define MFNR_GRAD2BLEND_2_LEN    5  
#define MFNR_GRAD2BLEND_2_OFFSET 0  

#define MFNR_GRAD2BLEND_3_LEN    5  
#define MFNR_GRAD2BLEND_3_OFFSET 0  

#define MFNR_GRAD2BLEND_4_LEN    5  
#define MFNR_GRAD2BLEND_4_OFFSET 0  

#define MFNR_GRAD2BLEND_5_LEN    5  
#define MFNR_GRAD2BLEND_5_OFFSET 0  

#define MFNR_GRAD2BLEND_6_LEN    5  
#define MFNR_GRAD2BLEND_6_OFFSET 0  

#define MFNR_GRAD2BLEND_7_LEN    5  
#define MFNR_GRAD2BLEND_7_OFFSET 0  

#define MFNR_GRAD2BLEND_8_LEN    5  
#define MFNR_GRAD2BLEND_8_OFFSET 0  

#define MFNR_GRAD2BLEND_9_LEN    5  
#define MFNR_GRAD2BLEND_9_OFFSET 0  

#define MFNR_GRAD2BLEND_10_LEN    5  
#define MFNR_GRAD2BLEND_10_OFFSET 0  

#define MFNR_GRAD2BLEND_11_LEN    5  
#define MFNR_GRAD2BLEND_11_OFFSET 0  

#define MFNR_GRAD2BLEND_12_LEN    5  
#define MFNR_GRAD2BLEND_12_OFFSET 0  

#define MFNR_GRAD2BLEND_13_LEN    5  
#define MFNR_GRAD2BLEND_13_OFFSET 0  

#define MFNR_GRAD2BLEND_14_LEN    5  
#define MFNR_GRAD2BLEND_14_OFFSET 0  

#define MFNR_GRAD2BLEND_15_LEN    5  
#define MFNR_GRAD2BLEND_15_OFFSET 0  

#define MFNR_GRAD2BLEND_16_LEN    5  
#define MFNR_GRAD2BLEND_16_OFFSET 0  

#define MFNR_GRAD2BLEND_17_LEN    5  
#define MFNR_GRAD2BLEND_17_OFFSET 0  

#define MFNR_GRAD2BLEND_18_LEN    5  
#define MFNR_GRAD2BLEND_18_OFFSET 0  

#define MFNR_GRAD2BLEND_19_LEN    5  
#define MFNR_GRAD2BLEND_19_OFFSET 0  

#define MFNR_GRAD2BLEND_20_LEN    5  
#define MFNR_GRAD2BLEND_20_OFFSET 0  

#define MFNR_GRAD2BLEND_21_LEN    5  
#define MFNR_GRAD2BLEND_21_OFFSET 0  

#define MFNR_GRAD2BLEND_22_LEN    5  
#define MFNR_GRAD2BLEND_22_OFFSET 0  

#define MFNR_GRAD2BLEND_23_LEN    5  
#define MFNR_GRAD2BLEND_23_OFFSET 0  

#define MFNR_GRAD2BLEND_24_LEN    5  
#define MFNR_GRAD2BLEND_24_OFFSET 0  

#define MFNR_GRAD2BLEND_25_LEN    5  
#define MFNR_GRAD2BLEND_25_OFFSET 0  

#define MFNR_GRAD2BLEND_26_LEN    5  
#define MFNR_GRAD2BLEND_26_OFFSET 0  

#define MFNR_GRAD2BLEND_27_LEN    5  
#define MFNR_GRAD2BLEND_27_OFFSET 0  

#define MFNR_GRAD2BLEND_28_LEN    5  
#define MFNR_GRAD2BLEND_28_OFFSET 0  

#define MFNR_GRAD2BLEND_29_LEN    5  
#define MFNR_GRAD2BLEND_29_OFFSET 0  

#define MFNR_GRAD2BLEND_30_LEN    5  
#define MFNR_GRAD2BLEND_30_OFFSET 0  

#define MFNR_GRAD2BLEND_31_LEN    5  
#define MFNR_GRAD2BLEND_31_OFFSET 0  

#define MFNR_SUM_DIFF_U_LEN    31 
#define MFNR_SUM_DIFF_U_OFFSET 0  

#define MFNR_SUM_DIFF_V_LEN    31 
#define MFNR_SUM_DIFF_V_OFFSET 0  

#define MFNR_GHOST_SIZE_LEN    23 
#define MFNR_GHOST_SIZE_OFFSET 0  

#define MFNR_GHOST_DETECT_TOP_DEBUG_LEN    32 
#define MFNR_GHOST_DETECT_TOP_DEBUG_OFFSET 0  

#define MFNR_GHOST_DETECT_GAUSS7X7_DEBUG_LEN    32 
#define MFNR_GHOST_DETECT_GAUSS7X7_DEBUG_OFFSET 0  

#define MFNR_GHOST_DETECT_DILATION_DEBUG_LEN    32 
#define MFNR_GHOST_DETECT_DILATION_DEBUG_OFFSET 0  

#define MFNR_GHOST_DETECT_GAUSS3X3_DEBUG_LEN    32 
#define MFNR_GHOST_DETECT_GAUSS3X3_DEBUG_OFFSET 0  

#define MFNR_GHOST_DETECT_US16_DEBUG_LEN    32 
#define MFNR_GHOST_DETECT_US16_DEBUG_OFFSET 0  

#define MFNR_DEGHOST_TOP_DEBUG_LEN    32 
#define MFNR_DEGHOST_TOP_DEBUG_OFFSET 0  

#endif // __MFNR_REG_OFFSET_FIELD_H__
