// ****************************************************************************** 
// Copyright     :  Copyright (C) 2018, Hisilicon Technologies Co., Ltd.
// File name     :  sub_ctrl_reg_offset_field.h
// Version       :  1.0 
// Date          :  2018-01-03
// Description   :  Define all registers/tables for HiStarISP
// Others        :  Generated automatically by nManager V4.0 
// ******************************************************************************

#ifndef __SUB_CTRL_REG_OFFSET_FIELD_H__
#define __SUB_CTRL_REG_OFFSET_FIELD_H__

#define SUB_CTRL_JPGENC_CLKEN_LEN    1  
#define SUB_CTRL_JPGENC_CLKEN_OFFSET 0  

#define SUB_CTRL_PREFETCH_STOP_JPGENC_LEN    1  
#define SUB_CTRL_PREFETCH_STOP_JPGENC_OFFSET 16 
#define SUB_CTRL_JPGENC_SOFT_RST_LEN         1  
#define SUB_CTRL_JPGENC_SOFT_RST_OFFSET      0  

#define SUB_CTRL_JPGENC_MEM_CTRL_LEN    32 
#define SUB_CTRL_JPGENC_MEM_CTRL_OFFSET 0  

#define SUB_CTRL_JPG_AXI_DLOCK_ID_LEN           8  
#define SUB_CTRL_JPG_AXI_DLOCK_ID_OFFSET        20 
#define SUB_CTRL_JPG_AXI_DLOCK_MST_LEN          1  
#define SUB_CTRL_JPG_AXI_DLOCK_MST_OFFSET       19 
#define SUB_CTRL_JPG_AXI_DLOCK_SLV_LEN          1  
#define SUB_CTRL_JPG_AXI_DLOCK_SLV_OFFSET       18 
#define SUB_CTRL_JPG_AXI_DLOCK_WR_LEN           1  
#define SUB_CTRL_JPG_AXI_DLOCK_WR_OFFSET        17 
#define SUB_CTRL_JPG_AXI_DLOCK_IRQ_LEN          1  
#define SUB_CTRL_JPG_AXI_DLOCK_IRQ_OFFSET       16 
#define SUB_CTRL_JPG_CVDR_BUSY_LEN              1  
#define SUB_CTRL_JPG_CVDR_BUSY_OFFSET           9  
#define SUB_CTRL_JPG_SMMU_IDLE_LEN              1  
#define SUB_CTRL_JPG_SMMU_IDLE_OFFSET           8  
#define SUB_CTRL_PREFETCH_STOP_OK_JPGDEC_LEN    1  
#define SUB_CTRL_PREFETCH_STOP_OK_JPGDEC_OFFSET 1  
#define SUB_CTRL_PREFETCH_STOP_OK_JPGENC_LEN    1  
#define SUB_CTRL_PREFETCH_STOP_OK_JPGENC_OFFSET 0  

#define SUB_CTRL_JPGDEC_FORCE_CLK_ON_LEN    1  
#define SUB_CTRL_JPGDEC_FORCE_CLK_ON_OFFSET 1  
#define SUB_CTRL_JPGDEC_CLKEN_LEN           1  
#define SUB_CTRL_JPGDEC_CLKEN_OFFSET        0  

#define SUB_CTRL_PREFETCH_STOP_JPGDEC_LEN    1  
#define SUB_CTRL_PREFETCH_STOP_JPGDEC_OFFSET 16 
#define SUB_CTRL_JPGDEC_SOFT_RST_LEN         1  
#define SUB_CTRL_JPGDEC_SOFT_RST_OFFSET      0  

#define SUB_CTRL_JPGDEC_MEM_CTRL_SP_LEN    32 
#define SUB_CTRL_JPGDEC_MEM_CTRL_SP_OFFSET 0  

#define SUB_CTRL_JPGDEC_IRQ_FORCE_LEN    4  
#define SUB_CTRL_JPGDEC_IRQ_FORCE_OFFSET 16 
#define SUB_CTRL_JPGDEC_IRQ_CLR_LEN      4  
#define SUB_CTRL_JPGDEC_IRQ_CLR_OFFSET   0  

#define SUB_CTRL_JPGDEC_IRQ_MASK_LEN    4  
#define SUB_CTRL_JPGDEC_IRQ_MASK_OFFSET 0  

#define SUB_CTRL_JPGDEC_IRQ_STATE_RAW_LEN     4  
#define SUB_CTRL_JPGDEC_IRQ_STATE_RAW_OFFSET  16 
#define SUB_CTRL_JPGDEC_IRQ_STATE_MASK_LEN    4  
#define SUB_CTRL_JPGDEC_IRQ_STATE_MASK_OFFSET 0  

#define SUB_CTRL_JPGDEC_MEM_CTRL_TP_LEN    16 
#define SUB_CTRL_JPGDEC_MEM_CTRL_TP_OFFSET 16 

#define SUB_CTRL_MST_PRIORITY_CVDR_LEN                   1  
#define SUB_CTRL_MST_PRIORITY_CVDR_OFFSET                18 
#define SUB_CTRL_MST_PRIORITY_FD_LEN                     1  
#define SUB_CTRL_MST_PRIORITY_FD_OFFSET                  17 
#define SUB_CTRL_CONTROL_DISABLE_AXI_DATA_PACKING_LEN    1  
#define SUB_CTRL_CONTROL_DISABLE_AXI_DATA_PACKING_OFFSET 16 
#define SUB_CTRL_JPG_SMMU_MASTER_CLKEN_LEN               1  
#define SUB_CTRL_JPG_SMMU_MASTER_CLKEN_OFFSET            4  
#define SUB_CTRL_JPG_TOP_APB_FORCE_CLK_ON_LEN            1  
#define SUB_CTRL_JPG_TOP_APB_FORCE_CLK_ON_OFFSET         3  
#define SUB_CTRL_JPG_DMA_FORCE_CLK_ON_LEN                1  
#define SUB_CTRL_JPG_DMA_FORCE_CLK_ON_OFFSET             2  
#define SUB_CTRL_JPG_SMMU_FORCE_CLK_ON_LEN               1  
#define SUB_CTRL_JPG_SMMU_FORCE_CLK_ON_OFFSET            1  
#define SUB_CTRL_JPG_DW_AXI_GATEDCLOCK_EN_LEN            1  
#define SUB_CTRL_JPG_DW_AXI_GATEDCLOCK_EN_OFFSET         0  

#define SUB_CTRL_CVDR_MEM_CTRL_LEN    32 
#define SUB_CTRL_CVDR_MEM_CTRL_OFFSET 0  

#define SUB_CTRL_CVDR_IRQ_FORCE_LEN    16 
#define SUB_CTRL_CVDR_IRQ_FORCE_OFFSET 16 
#define SUB_CTRL_CVDR_IRQ_CLR_LEN      16 
#define SUB_CTRL_CVDR_IRQ_CLR_OFFSET   0  

#define SUB_CTRL_CVDR_IRQ_MASK_LEN    16 
#define SUB_CTRL_CVDR_IRQ_MASK_OFFSET 0  

#define SUB_CTRL_CVDR_IRQ_STATE_RAW_LEN     16 
#define SUB_CTRL_CVDR_IRQ_STATE_RAW_OFFSET  16 
#define SUB_CTRL_CVDR_IRQ_STATE_MASK_LEN    16 
#define SUB_CTRL_CVDR_IRQ_STATE_MASK_OFFSET 0  

#define SUB_CTRL_SMMU_MASTER_SOFT_RST_LEN    1  
#define SUB_CTRL_SMMU_MASTER_SOFT_RST_OFFSET 2  
#define SUB_CTRL_SMMU_SOFT_RST_LEN           1  
#define SUB_CTRL_SMMU_SOFT_RST_OFFSET        1  
#define SUB_CTRL_CVDR_SOFT_RST_LEN           1  
#define SUB_CTRL_CVDR_SOFT_RST_OFFSET        0  

#define SUB_CTRL_MERGED_IRQ_STATE_LEN    24 
#define SUB_CTRL_MERGED_IRQ_STATE_OFFSET 0  

#define SUB_CTRL_AP_IRQ_STATE_LEN    11 
#define SUB_CTRL_AP_IRQ_STATE_OFFSET 21 


#define SUB_CTRL_FD_MEM_CTRL_TP_LEN    16 
#define SUB_CTRL_FD_MEM_CTRL_TP_OFFSET 16 
#define SUB_CTRL_FD_ROM_CTRL_LEN       8  
#define SUB_CTRL_FD_ROM_CTRL_OFFSET    8  
#define SUB_CTRL_FD_ARQOS_LEN          2  
#define SUB_CTRL_FD_ARQOS_OFFSET       2  
#define SUB_CTRL_FD_AWQOS_LEN          2  
#define SUB_CTRL_FD_AWQOS_OFFSET       0  

#define SUB_CTRL_FD_FUNC_CLKEN_LEN    1  
#define SUB_CTRL_FD_FUNC_CLKEN_OFFSET 2  
#define SUB_CTRL_FD_AXIM_CLKEN_LEN    1  
#define SUB_CTRL_FD_AXIM_CLKEN_OFFSET 1  
#define SUB_CTRL_FD_APBM_CLKEN_LEN    1  
#define SUB_CTRL_FD_APBM_CLKEN_OFFSET 0  

#define SUB_CTRL_FD_FUNC_SOFT_RST_LEN    1  
#define SUB_CTRL_FD_FUNC_SOFT_RST_OFFSET 2  
#define SUB_CTRL_FD_AXIM_SOFT_RST_LEN    1  
#define SUB_CTRL_FD_AXIM_SOFT_RST_OFFSET 1  
#define SUB_CTRL_FD_APBM_SOFT_RST_LEN    1  
#define SUB_CTRL_FD_APBM_SOFT_RST_OFFSET 0  

#define SUB_CTRL_FD_MEM_CTRL_SP_LEN    32 
#define SUB_CTRL_FD_MEM_CTRL_SP_OFFSET 0  

#define SUB_CTRL_FLUX_CTRL0_CVDR_R_LEN    32 
#define SUB_CTRL_FLUX_CTRL0_CVDR_R_OFFSET 0  

#define SUB_CTRL_FLUX_CTRL1_CVDR_R_LEN    32 
#define SUB_CTRL_FLUX_CTRL1_CVDR_R_OFFSET 0  

#define SUB_CTRL_FLUX_CTRL0_CVDR_W_LEN    32 
#define SUB_CTRL_FLUX_CTRL0_CVDR_W_OFFSET 0  

#define SUB_CTRL_FLUX_CTRL1_CVDR_W_LEN    32 
#define SUB_CTRL_FLUX_CTRL1_CVDR_W_OFFSET 0  

#define SUB_CTRL_FLUX_CTRL0_FD_R_LEN    32 
#define SUB_CTRL_FLUX_CTRL0_FD_R_OFFSET 0  

#define SUB_CTRL_FLUX_CTRL1_FD_R_LEN    32 
#define SUB_CTRL_FLUX_CTRL1_FD_R_OFFSET 0  

#define SUB_CTRL_FLUX_CTRL0_FD_W_LEN    32 
#define SUB_CTRL_FLUX_CTRL0_FD_W_OFFSET 0  

#define SUB_CTRL_FLUX_CTRL1_FD_W_LEN    32 
#define SUB_CTRL_FLUX_CTRL1_FD_W_OFFSET 0  

#define SUB_CTRL_FD_PREFETCH_INITIAL_LEN    11 
#define SUB_CTRL_FD_PREFETCH_INITIAL_OFFSET 0  

#define SUB_CTRL_FD_STREAM_END_LEN    11 
#define SUB_CTRL_FD_STREAM_END_OFFSET 0  

#define SUB_CTRL_FD_STREAM_ACK_LEN    11 
#define SUB_CTRL_FD_STREAM_ACK_OFFSET 0  

#define SUB_CTRL_HIFD_FUNC_CLKEN_LEN    1  
#define SUB_CTRL_HIFD_FUNC_CLKEN_OFFSET 2  
#define SUB_CTRL_HIFD_AXIM_CLKEN_LEN    1  
#define SUB_CTRL_HIFD_AXIM_CLKEN_OFFSET 1  
#define SUB_CTRL_HIFD_APBM_CLKEN_LEN    1  
#define SUB_CTRL_HIFD_APBM_CLKEN_OFFSET 0  

#define SUB_CTRL_HIFD_FUNC_SOFT_RST_LEN    1  
#define SUB_CTRL_HIFD_FUNC_SOFT_RST_OFFSET 2  
#define SUB_CTRL_HIFD_AXIM_SOFT_RST_LEN    1  
#define SUB_CTRL_HIFD_AXIM_SOFT_RST_OFFSET 1  
#define SUB_CTRL_HIFD_APBM_SOFT_RST_LEN    1  
#define SUB_CTRL_HIFD_APBM_SOFT_RST_OFFSET 0  

#define SUB_CTRL_DEBUG_INFO_0_LEN    32 
#define SUB_CTRL_DEBUG_INFO_0_OFFSET 0  

#define SUB_CTRL_DEBUG_INFO_1_LEN    32 
#define SUB_CTRL_DEBUG_INFO_1_OFFSET 0  

#define SUB_CTRL_DEBUG_INFO_2_LEN    32 
#define SUB_CTRL_DEBUG_INFO_2_OFFSET 0  

#define SUB_CTRL_DEBUG_INFO_3_LEN    32 
#define SUB_CTRL_DEBUG_INFO_3_OFFSET 0  

#define SUB_CTRL_SLAM_CLKEN_LEN    1  
#define SUB_CTRL_SLAM_CLKEN_OFFSET 0  

#define SUB_CTRL_SLAM_SOFT_RST_LEN    1  
#define SUB_CTRL_SLAM_SOFT_RST_OFFSET 0  

#define SUB_CTRL_SLAM_FORCE_CLK_ON_LEN    1  
#define SUB_CTRL_SLAM_FORCE_CLK_ON_OFFSET 0  

#define SUB_CTRL_SLAM_PWR_MEM_CTRL_SP_LEN    3  
#define SUB_CTRL_SLAM_PWR_MEM_CTRL_SP_OFFSET 0  

#define SUB_CTRL_SLAM_COMP_EOF_SOURCE_EN_LEN    4  
#define SUB_CTRL_SLAM_COMP_EOF_SOURCE_EN_OFFSET 0  

#define SUB_CTRL_SLAM_COMP_EOF_RAW_EN_LEN    2  
#define SUB_CTRL_SLAM_COMP_EOF_RAW_EN_OFFSET 0  

#define SUB_CTRL_CMDLST_CLKEN_LEN    1  
#define SUB_CTRL_CMDLST_CLKEN_OFFSET 2  
#define SUB_CTRL_MFNR_CLKEN_LEN      1  
#define SUB_CTRL_MFNR_CLKEN_OFFSET   1  
#define SUB_CTRL_MCF_CLKEN_LEN       1  
#define SUB_CTRL_MCF_CLKEN_OFFSET    0  

#define SUB_CTRL_CMDLST_SOFT_RST_LEN    1  
#define SUB_CTRL_CMDLST_SOFT_RST_OFFSET 2  
#define SUB_CTRL_MFNR_SOFT_RST_LEN      1  
#define SUB_CTRL_MFNR_SOFT_RST_OFFSET   1  
#define SUB_CTRL_MCF_SOFT_RST_LEN       1  
#define SUB_CTRL_MCF_SOFT_RST_OFFSET    0  

#define SUB_CTRL_MFNR_FORCE_CLK_ON_LEN    1  
#define SUB_CTRL_MFNR_FORCE_CLK_ON_OFFSET 1  
#define SUB_CTRL_MCF_FORCE_CLK_ON_LEN     1  
#define SUB_CTRL_MCF_FORCE_CLK_ON_OFFSET  0  

#define SUB_CTRL_CMDLST_EC_FUNC_EN_LEN     2  
#define SUB_CTRL_CMDLST_EC_FUNC_EN_OFFSET  30 
#define SUB_CTRL_COMMON_MEM_CTRL_SP_LEN    27 
#define SUB_CTRL_COMMON_MEM_CTRL_SP_OFFSET 3  

#define SUB_CTRL_MCF_PWR_MEM_CTRL_SP_LEN    3  
#define SUB_CTRL_MCF_PWR_MEM_CTRL_SP_OFFSET 0  

#define SUB_CTRL_MFNR_PWR_MEM_CTRL_SP_LEN    3  
#define SUB_CTRL_MFNR_PWR_MEM_CTRL_SP_OFFSET 0  

#define SUB_CTRL_CPE_VPWR0_IHRIGHT_LEN    11 
#define SUB_CTRL_CPE_VPWR0_IHRIGHT_OFFSET 16 
#define SUB_CTRL_CPE_VPWR0_IHLEFT_LEN     11 
#define SUB_CTRL_CPE_VPWR0_IHLEFT_OFFSET  0  

#define SUB_CTRL_CPE_VPWR1_IHRIGHT_LEN    11 
#define SUB_CTRL_CPE_VPWR1_IHRIGHT_OFFSET 16 
#define SUB_CTRL_CPE_VPWR1_IHLEFT_LEN     11 
#define SUB_CTRL_CPE_VPWR1_IHLEFT_OFFSET  0  

#define SUB_CTRL_CPE_VPWR2_IHRIGHT_LEN    11 
#define SUB_CTRL_CPE_VPWR2_IHRIGHT_OFFSET 16 
#define SUB_CTRL_CPE_VPWR2_IHLEFT_LEN     11 
#define SUB_CTRL_CPE_VPWR2_IHLEFT_OFFSET  0  

#define SUB_CTRL_CPE_OP_MODE_LEN    1  
#define SUB_CTRL_CPE_OP_MODE_OFFSET 0  

#define SUB_CTRL_CPE_IRQ0_CLR_LEN    1  
#define SUB_CTRL_CPE_IRQ0_CLR_OFFSET 0  

#define SUB_CTRL_CPE_IRQ0_FORCE_LEN    1  
#define SUB_CTRL_CPE_IRQ0_FORCE_OFFSET 0  

#define SUB_CTRL_CPE_IRQ0_MASK_LEN    1  
#define SUB_CTRL_CPE_IRQ0_MASK_OFFSET 0  

#define SUB_CTRL_CPE_IRQ0_RAW_LEN    1  
#define SUB_CTRL_CPE_IRQ0_RAW_OFFSET 0  

#define SUB_CTRL_CPE_IRQ0_STAT_LEN    1  
#define SUB_CTRL_CPE_IRQ0_STAT_OFFSET 0  

#define SUB_CTRL_CPE_IRQ1_CLR_LEN    29 
#define SUB_CTRL_CPE_IRQ1_CLR_OFFSET 0  

#define SUB_CTRL_CPE_IRQ1_FORCE_LEN    29 
#define SUB_CTRL_CPE_IRQ1_FORCE_OFFSET 0  

#define SUB_CTRL_CPE_IRQ1_MASK_LEN    29 
#define SUB_CTRL_CPE_IRQ1_MASK_OFFSET 0  

#define SUB_CTRL_CPE_IRQ1_RAW_LEN    29 
#define SUB_CTRL_CPE_IRQ1_RAW_OFFSET 0  

#define SUB_CTRL_CPE_IRQ1_STAT_LEN    29 
#define SUB_CTRL_CPE_IRQ1_STAT_OFFSET 0  

#define SUB_CTRL_CPE_COMP_EOF_SOURCE_EN_LEN    14 
#define SUB_CTRL_CPE_COMP_EOF_SOURCE_EN_OFFSET 0  

#define SUB_CTRL_CPE_COMP_EOF_RAW_EN_LEN    2  
#define SUB_CTRL_CPE_COMP_EOF_RAW_EN_OFFSET 0  

#define SUB_CTRL_SLAM_TZ_SECURE_N_LEN      1  
#define SUB_CTRL_SLAM_TZ_SECURE_N_OFFSET   5  
#define SUB_CTRL_CPE_TZ_SECURE_N_LEN       1  
#define SUB_CTRL_CPE_TZ_SECURE_N_OFFSET    4  
#define SUB_CTRL_FD_TZ_SECURE_N_LEN        1  
#define SUB_CTRL_FD_TZ_SECURE_N_OFFSET     3  
#define SUB_CTRL_JPGDEC_TZ_SECURE_N_LEN    1  
#define SUB_CTRL_JPGDEC_TZ_SECURE_N_OFFSET 2  
#define SUB_CTRL_JPGENC_TZ_SECURE_N_LEN    1  
#define SUB_CTRL_JPGENC_TZ_SECURE_N_OFFSET 1  
#define SUB_CTRL_TOP_TZ_SECURE_N_LEN       1  
#define SUB_CTRL_TOP_TZ_SECURE_N_OFFSET    0  

#define SUB_CTRL_FD_AXI_PROT_LEN    3  
#define SUB_CTRL_FD_AXI_PROT_OFFSET 8  

#endif // __SUB_CTRL_REG_OFFSET_FIELD_H__
